# These are supported funding model platforms

ko_fi: e3kskoy7wqk
custom: ['https://github.com/e3kskoy7wqk/Firefox-for-windows-7/blob/master/imgs/mm_facetoface_collect_qrcode_1743308063603.png', 'https://github.com/e3kskoy7wqk/Firefox-for-windows-7/blob/master/imgs/1743308083.jpg']
